---
title: "Module 2, Assignment 3"
author: "Ellen Bledsoe"
date: "2022-10-04"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r message = FALSE}
library(tidyverse)
```

2.  

```{r}
growth <- read_csv("../data/tilapia_growth.csv")
head(growth)
tail(growth)
```

5.  

```{r}
growth <- growth %>% 
  mutate(day_30_weight_kg = day_30_weight / 1000)
as_tibble(growth)
```

6.  

```{r}
growth_by_treatment <- growth %>% 
  group_by(perc_soy_protein) %>% 
  summarize(mean_weight_kg = mean(day_30_weight_kg))
as_tibble(growth_by_treatment)
```

7.  

```{r}
plot(x = growth$perc_soy_protein, y = growth$day_30_weight_kg,
     xlab = "[insert axis title here]", ylab = "[insert axis title here]")
```

8.  

```{r}
growth <- growth %>% 
  mutate(tank_category = if_else(avg_tank_temp >= 75, "warm", "cold"))
as_tibble(growth)
```

9.  

```{r}
growth_by_treatment_and_temp <- growth %>% 
  group_by(perc_soy_protein, tank_category) %>% 
  summarise(mean_weight_kg = mean(day_30_weight_kg))
as_tibble(growth_by_treatment_and_temp)
```

10. 

```{r}
plot(x = growth$avg_tank_temp, y = growth$day_30_weight_kg,
     xlab = "[insert axis title here]", ylab = "[insert axis title here]")
```
