---
title: "Module 2, Assignment 2"
author: "Ellen Bledsoe"
date: "`r Sys.Date()`"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

1.  

```{r messsage = FALSE}
library(tidyverse)
```

2.

```{r}
growth <- read_csv("../data/tilapia_growth.csv")
head(growth)
tail(growth)

growth <- growth %>% 
  mutate(soy_protein = factor(soy_protein, levels = c("low", "medium", "high", "very high")))
```


5.

```{r}
growth <- growth %>%
  mutate(day_30_weight_kg = day_30_weight / 1000)
print.data.frame(head(growth, 10))
```

6.

```{r}
growth_by_treatment <- growth %>%
  group_by(soy_protein) %>%
  summarize(mean_weight_kg = mean(day_30_weight_kg))
growth_by_treatment
```

7.

```{r}
ggplot(growth, aes(soy_protein, day_30_weight_kg)) +
  geom_boxplot() +
  geom_jitter(width = 0.1) +
  labs(x = "Amount of Soy Protein in Diet",
   y = "Tilapia Weight at 30 Days (kg)") +
  theme_light()
```

8.

```{r}
growth_by_treatment_and_temp <- growth %>%
  group_by(soy_protein, tank_category) %>%
  summarise(mean_weight_kg = mean(day_30_weight_kg))
growth_by_treatment_and_temp
```

9.

```{r}
ggplot(growth, aes(avg_tank_temp, day_30_weight_kg, color = soy_protein)) +
  geom_point() +
  labs(x = "Average Tank Temperature (C)",
   y = "Tilapia Weight at 30 Days (kg)",
   color = "Amount of Soy Protein") +
  theme_light()
```
