---
title: "Module 2, Assignment 3"
author: "Ellen Bledsoe"
date: "2022-10-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Assignment Details

### Purpose

The goal of this assignment is to practice developing successful workflows to get from the starting data to a plot.

### Task

Write R code which produces the correct answers and reflect on workflow.

### Criteria for Success

-   Code is within the provided code chunks
-   Code is commented with brief descriptions of what the code does
-   Code chunks run without errors
-   Code produces the correct result
    -   Code that produces the correct answer will receive full credit
    -   Code attempts with logical direction will receive partial credit
-   Written answers address the questions in sufficient detail

### Due Date

October 11 at midnight MST

# Assignment Questions

Our goal for this assignment is to start with a dataframe, summarize the data in constructive ways and plot the data. To get from point a to point b to point c requires some planning. In this assignment, we will make a plan, execute how we would actually go about the process, and then evaluate how well our original plan matches with the path we actually used.

First, let's take a look at the data we will be using for the assignment. Use the `head` function to get an idea of what the data look like.
