---
title: 'Module 3: Assignment 3'
author: "Ellen Bledsoe"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Assignment Details

### Purpose

The goal of this assignment is to assess your ability to use the appropriate statistical test for comparing means between groups and make decisions based on the interpretation of the results.

### Task

Write R code which produces the correct answers and correctly interpret the results of visualizations and statistical tests.

### Criteria for Success

-   Code is within the provided code chunks
-   Code is commented with brief descriptions of what the code does
-   Code chunks run without errors
-   Code produces the correct result
    -   Code that produces the correct answer will receive full credit
    -   Code attempts with logical direction will receive partial credit
-   Written answers address the questions in sufficient detail

### Due Date

April 4 at midnight MST

# Assignment Questions

For this assignment, we will be using some data about solar panels.

In addition to our wind turbines that are creating energy, we are also testing out solar panels from many different companies. 

We've set up solar panels on two different sides of the station: the north and the south. The plan is to first compare the solar panels companies on the north side to see which company's panels are creating the most energy. From there, we will do the same with the solar panel companies from the southern side.

Once the top company has been chosen from either side, we will run another test with the top two companies in the same location and choose the best one.

## Set-Up

## The North Side

## The South Side

## The Final Test

